#' Brass PF Function
#'
#' @param ages A vector of starting ages of five-year age groups ranging from 15 to 45
#' @param P A vector of mean parities by five-year age group - same groups as 'ages'
#' @param asfr A vector of age-specific fertility rates by five-year age group - same groups as 'ages'
#' @param adjust_group A vector of age-groups from 'ages' to be used for selection of PF ratios to adjust asfr data
#'
#' @return A list with 3 elements:
#' pf_data data frame with columns ages, P for mean parities, asfr, Fi for cumulate fertility estimated from Brass coefficients,PF for ratios P/F and adj_asfr for adjusted asfr;
#' tfr_unadj for unadjusted total fertility rate estimate;
#' and tfr_adj for adjusted total fertility rate estimate by applying the selected age-group PF ratio
#'
#' @examples
#' ## Malawi 2008 Census data:
#' ages_ma = c(15, 20, 25, 30, 35, 40, 45)
#' asfr_ma = c(0.111, 0.245, 0.230, 0.195, 0.147, 0.072, 0.032)
#' P_ma    = c(0.283, 1.532, 2.849, 4.185, 5.214, 6.034, 6.453)
#' brass_pf(P = P_ma, asfr = asfr_ma)
#'
#'

brass_pf <-
  function( ages = seq(15,45,5),
            P,
            asfr,
            adjust_group = c(20)){

  # INPUTS:
  ## ages : 5 year age group from 15 to 49 as a vector c(15,20,25,30,35,40,45) by default
  ## P    : mean number of children ever born to women from age group x
  ## asfr : age specific fertility rates of age group x

  # 1. Check if inputs have the correct dimensions
  check.inputs <-
    function( ages , P , asfr ){
      if (length(ages)!=7 | length(P)!=7 | length(asfr)!=7){
        stop('Wrong dimension of inputs - please check if lengths==7')
      }
      if ( sum(ages == seq(15,45,5) ) != 7){
        stop('Vector ages is not in the correct format, try ages = seq(15,45,5)')
      }
  }

  check.inputs( ages , P , asfr )

  # 2. Create a matrix with three input vectors
  pf_data <-
    data.frame( ages , P , asfr)

  # 3. Compute mean age at respective age group
  ages_mean <-
    pf_data$ages + 2.5

  # 4. Compute mean age at motherhood
  mean_age_moth <-
    sum(ages_mean*pf_data$asfr)/sum(pf_data$asfr)

  # 5. Compute ratio P(1)/P(2)
  p_ratio <-
    pf_data$P[1] / pf_data$P[2]

  # 6. Entry of multipliers matrix
  mult_data <-
    data.frame(
      ages = c( "15-19" , "20-24" , "25-29" , "30-34" , "35-39" , "40-44" , "45-49" , "P1/P2" , "f1/f2" , "m"),
      Int1 = c( 1.120 , 2.555 , 2.925 , 3.055 , 3.165 , 3.325 , 3.640 , 0.014 , 0.036 , 31.7),
      Int2 = c( 1.310 , 2.690 , 2.960 , 3.075 , 3.190 , 3.375 , 3.895 , 0.045 , 0.113 , 30.7),
      Int3 = c( 1.615 , 2.780 , 2.985 , 3.095 , 3.215 , 3.435 , 4.150 , 0.090 , 0.213 , 29.7),
      Int4 = c( 1.950 , 2.840 , 3.010 , 3.120 , 3.245 , 3.510 , 4.395 , 0.143 , 0.330 , 28.7),
      Int5 = c( 2.305 , 2.890 , 3.035 , 3.140 , 3.285 , 3.610 , 4.630 , 0.205 , 0.460 , 27.7),
      Int6 = c( 2.640 , 2.925 , 3.055 , 3.165 , 3.325 , 3.740 , 4.840 , 0.268 , 0.605 , 26.7),
      Int7 = c( 2.925 , 2.960 , 3.075 , 3.190 , 3.375 , 3.915 , 4.985 , 0.330 , 0.764 , 25.7),
      Int8 = c( 3.170 , 2.985 , 3.095 , 3.215 , 3.435 , 4.150 , 5.000 , 0.387 , 0.939 , 24.7)
      )

  # 7. Find the interval in which the p_ratio lies in
  int.p <-
    findInterval(
      p_ratio,
      mult_data[ 8 , 2:9 ]
    )

  # 8. Find alpha.1 by interpolation of p_ratio
  alpha.1 <-
    ( p_ratio - mult_data[ 8 , ( int.p + 1 ) ] ) / ( mult_data[ 8 , ( int.p + 2 ) ] - mult_data[ 8 , ( int.p + 1 ) ] )

  # 9. Three first age groups coefficients are generated by interpolation with alpha.1
  group.1 <-
    mult_data[ 1:3 , ( int.p + 1 ) : ( int.p + 2 ) ]

  group.1$ks <-
    alpha.1 * ( group.1[ , 2 ] - group.1[ , 1 ] ) + group.1[ , 1 ]

  # 10. Find the interval in which the mean age at motherhood lies in
  int.m <-
    8 -
    findInterval(
      mean_age_moth,
      sort(mult_data[10,2:9])
    )

  # 11. If mean age at motherhood is higher than upper bound, add it into the last interval 30.7-31.7
  if ( int.m == 8 ){
    warning('Mean age of motherhood is greater than 31.7')
    int.m <- 7
  }

  # 12. Compute alpha.2 by interpolation of mean age at motherhood with found age interval
  alpha.2 <-
    ( mean_age_moth - mult_data[ 10 , ( int.m + 1 ) ] ) /
    ( mult_data[ 10 , ( int.m + 2 ) ] - mult_data[ 10 , ( int.m + 1 ) ] )

  # 13. Four age groups coefficients are generated by interpolation with alpha.2
  group.2 <-
    mult_data[ 4:7 , ( int.m + 1 ) : ( int.m + 2 ) ]

  group.2$ks <-
    alpha.2 * ( group.2[ , 2 ] - group.2[ , 1 ] ) + group.2[ , 1 ]

  # 14. Create coefficients vector and add to data
  pf_data$ki <-
    c( group.1$ks , group.2$ks )

  # 15. Cumulate asfr for Fi estimation
  pf_data$delta <- 0

  for ( i in 1:6 ) {
    pf_data[ i+1 , 'delta'] <-
      ( pf_data[ i , 'asfr' ] ) * 5 + ( pf_data[ i , 'delta' ] )
  }

  # 16. Multiply coefficients ki by asfr and add to delta to estimate Fi
  pf_data$Fi <-
    pf_data$delta + pf_data$ki * pf_data$asfr

  # 17. Compute PF ratios
  pf_data$PF <-
    pf_data$P / pf_data$Fi

  # 18. Adjust asfr by selected age groups PF ratio mean (default = 20-24)
  pf_data$adj_asfr <-
    mean( pf_data$PF[ ages %in% adjust_group ] ) * pf_data$asfr

  # 19. set returning list of results
  pf_output <-
    list(
      pf_data   = pf_data[,c('ages', 'P', 'asfr', 'Fi', 'PF', 'adj_asfr')],
      tfr_unadj = sum( pf_data$asfr*5 ),
      tfr_adj   = sum( pf_data$adj_asfr*5 )
    )

  return(pf_output)
}
